services:
  calculator.api:
    build:
      context: .
      dockerfile: DockerfileCalculatorApi
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure

  emissions.api:
    build:
      context: .
      dockerfile: DockerfileEmissionsApi
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure

  measurements.api:
    build:
      context: .
      dockerfile: DockerfileMeasurementsApi
    ports:
      - "7002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure

networks:
  productnetwork:

